import copy
import json

import pytest

from tools.outcome_prediction import wm_matched_evidence as evidence


def example(source=None, selection=None, family="sft", command=None):
    data = {key: value for key, value in (("source", source), ("selection", selection), ("build_command", command)) if value is not None}
    return {"model_input": {"plan": {"setup": {"method": {"family": family}, "data": [data]}}, "code": []},
            "history": []}


def flags(value, scope="current"):
    return evidence.extract(value)["context"][scope]["evidence"]


def test_fixed_positive_only_schema():
    result = evidence.extract(example())
    assert set(result) == {"context", "provenance"}
    assert set(result["context"]) == {"schema", "current", "immediate_parent"}
    step = result["context"]["current"]
    assert set(step) == {"status", "family_tokens", "objective", "evidence"}
    assert tuple(step["evidence"]) == evidence.EVIDENCE_KEYS
    assert all(value is None for value in step["evidence"].values())
    assert result["context"]["immediate_parent"]["status"] == "no_parent_recipe"


@pytest.mark.parametrize("family,tokens,objective", [
    ("sft", ["sft"], "supervised_token_training"),
    ("sft_continued", ["sft"], "supervised_token_training"),
    ("RFT", ["rft"], "supervised_token_training"),
    ("distillation", ["distill"], "supervised_token_training"),
    ("sft + rft", ["rft", "sft"], "supervised_token_training"),
    ("GRPO", ["grpo"], "unknown"),
    ("SFT then PPO", ["ppo", "sft"], "unknown"),
    ("private secret unknown", [], "unknown"),
    (None, [], "unknown"),
])
def test_family_is_normalized_and_objective_is_cohort_grouping(family, tokens, objective):
    step = evidence.extract(example(family=family))["context"]["current"]
    assert step["family_tokens"] == tokens
    assert step["objective"] == objective
    assert all(v is None for v in step["evidence"].values())


@pytest.mark.parametrize("text,field", [
    ("synthetic:self from a prior model", "self_sampled"),
    ("self-generated data", "self_sampled"),
    ("on-policy completions", "self_sampled"),
    ("answer-verified samples", "correctness_selection"),
    ("gold-verified samples", "correctness_selection"),
    ("keep only samples whose answer matches the gold", "correctness_selection"),
    ("shortest correct RFT solution", "correctness_selection"),
    ("rejection-sampled correct solutions", "correctness_selection"),
    ("on-policy correct solutions", "correctness_selection"),
    ("correct first-answer, truncated", "correctness_selection"),
    ("correct-slot top-ups", "correctness_selection"),
    ("keep last-number==gold", "correctness_selection"),
    ("fills the third slot with a wrong on-policy attempt", "wrong_attempts"),
    ("include incorrect solutions", "wrong_attempts"),
    ("gold reasoning as replay", "gold_replay"),
    ("gold reasoning; anchor to prevent drift", "gold_replay"),
    ("plus gold GSM8K training data", "gold_replay"),
    ("teacher-generated samples", "teacher_generated"),
    ("generated by a teacher", "teacher_generated"),
])
def test_positive_source_and_selection_declarations(text, field):
    for value in (example(source=text), example(selection=text)):
        assert flags(value)[field] is True


@pytest.mark.parametrize("text,field", [
    ("no self-generated samples", "self_sampled"),
    ("not using self-generated data", "self_sampled"),
    ("without any on-policy data", "self_sampled"),
    ("self-generated samples are not used", "self_sampled"),
    ("no answer-verified samples", "correctness_selection"),
    ("not shortest correct RFT solutions", "correctness_selection"),
    ("never include wrong attempts", "wrong_attempts"),
    ("include no wrong attempts", "wrong_attempts"),
    ("do not retain incorrect solutions", "wrong_attempts"),
    ("wrong on-policy attempts are discarded", "wrong_attempts"),
    ("without gold replay", "gold_replay"),
    ("no teacher-generated data", "teacher_generated"),
    ("evaluation-only self-generated data", "self_sampled"),
    ("for evaluation use teacher-generated samples", "teacher_generated"),
])
def test_negation_and_nontraining_scope_stay_unknown(text, field):
    assert flags(example(source=text))[field] is None


def test_correctness_is_not_self_generation_or_exclusive_purity():
    result = flags(example(source="external answer-verified samples"))
    assert result["correctness_selection"] is True
    assert result["self_sampled"] is None
    mixed = flags(example(source="self-generated; keep correct samples; include wrong attempts"))
    assert mixed["self_sampled"] is mixed["correctness_selection"] is mixed["wrong_attempts"] is True


@pytest.mark.parametrize("command", [
    ["python", "builder.py", "--wrong-frac", "0.5"],
    "python builder.py --wrong-frac=0.5",
    ["python", "builder.py", "--incorrect_fraction", "1"],
])
def test_explicit_positive_builder_wrong_fraction(command):
    assert flags(example(command=command))["wrong_attempts"] is True


@pytest.mark.parametrize("command", [
    ["python", "builder.py", "--wrong-frac", "0"],
    ["python", "builder.py", "--wrong-frac", "-0.5"],
    ["python", "builder.py", "--wrong-frac", "NaN"],
    ["python", "builder.py", "--wrong-frac", "2"],
    ["python", "builder.py", "--wrong-frac", "0.5", "--wrong-frac", "0"],
    ["python", "builder.py", "--wrong-frac"],
    "python builder.py --wrong-frac 0.5 && python eval.py",
    "unterminated '\"",
])
def test_wrong_fraction_unknown_zero_invalid_or_ambiguous(command):
    assert flags(example(command=command))["wrong_attempts"] is None


def test_outcomes_rawtext_code_and_nondata_plan_fields_never_forwarded():
    value = example(source="CANARY 0.987654321 answer-verified source /PRIVATE/path")
    value.update(example_id="SECRET_ID", accuracy=0.456789, parent={"accuracy": 0.543219})
    value["model_input"]["plan"].update(result={"accuracy": 0.777888}, analysis="self-generated")
    value["model_input"]["plan"]["setup"]["method"]["target_format"] = "teacher-generated"
    value["model_input"]["code"] = [{"role": "data_builder_0", "status": "reconstructed", "content": "# self-generated\nwrong_frac = 0.9"}]
    encoded = json.dumps(evidence.extract(value))
    assert not any(token in encoded for token in ("CANARY", "987654321", "PRIVATE", "SECRET_ID", "456789", "543219", "777888"))
    result = flags(value)
    assert result["correctness_selection"] is True
    assert result["self_sampled"] is result["teacher_generated"] is result["wrong_attempts"] is None


def test_only_immediate_screened_parent_not_current_or_older_backfill():
    value = example(source="teacher-generated")
    older = example(source="self-generated")["model_input"]
    value["history"] = [{"recipe_status": "screened", "model_input": older},
                        {"recipe_status": "quarantined", "model_input": older}]
    result = evidence.extract(value)["context"]
    assert result["current"]["evidence"]["teacher_generated"] is True
    assert result["immediate_parent"]["status"] == "quarantined"
    assert all(v is None for v in result["immediate_parent"]["evidence"].values())
    value["history"][-1] = {"recipe_status": "screened", "model_input": older}
    assert flags(value, "immediate_parent")["self_sampled"] is True
    assert flags(value, "immediate_parent")["teacher_generated"] is None


def test_extraction_does_not_mutate_input_and_provenance_is_separate():
    value = example(source="self-generated plus gold GSM8K train")
    before = copy.deepcopy(value)
    result = evidence.extract(value)
    assert value == before
    assert "sha256" not in json.dumps(result["context"])
    assert result["provenance"]["current"]["fields"][0]["sha256"]


def test_missing_current_and_unknown_parent_status():
    result = evidence.extract({"history": [{"recipe_status": "unscreened", "model_input": example()["model_input"]}]})
    assert result["context"]["current"]["status"] == "missing_recipe"
    assert result["context"]["immediate_parent"]["status"] == "missing_recipe"


def test_validate_context_accepts_only_canonical_output_without_mutation():
    context = evidence.extract(example(source="self-generated"))["context"]
    before = copy.deepcopy(context)
    assert evidence.validate_context(context) == before
    assert context == before


@pytest.mark.parametrize("mutation", [
    lambda x: x.update(accuracy=0.9),
    lambda x: x.update(schema="unknown"),
    lambda x: x["current"].update(raw_source="private data"),
    lambda x: x["current"].update(status="invented"),
    lambda x: x["current"].update(family_tokens=["sft", "sft"]),
    lambda x: x["current"].update(family_tokens=["sft", "rft"]),
    lambda x: x["current"].update(family_tokens=["SECRET"]),
    lambda x: x["current"].update(family_tokens=[0.987]),
    lambda x: x["current"].update(family_tokens=["grpo"]),
    lambda x: x["current"].update(objective="unknown"),
    lambda x: x["current"]["evidence"].update(accuracy=0.8),
    lambda x: x["current"]["evidence"].update(self_sampled=False),
    lambda x: x["current"]["evidence"].update(self_sampled=1),
    lambda x: x["current"]["evidence"].update(self_sampled="true"),
    lambda x: x["immediate_parent"]["evidence"].update(self_sampled=True),
    lambda x: x.update(current=None),
])
def test_validate_context_rejects_new_fields_outcomes_enums_and_fake_evidence(mutation):
    context = evidence.extract(example())["context"]
    mutation(context)
    with pytest.raises(ValueError):
        evidence.validate_context(context)
