#!/usr/bin/env python3
"""Generated by awm/adapters/airs.py -- turn upstream evaluate.py's stdout into a reward.

Upstream ships no normalisation code (harness_facts/airs_bench.md section 4): the paper
defines the formula, the repo does not implement it. The formula below is a verbatim
copy of awm/adapters/airs.py's, so the two cannot drift.
"""

from __future__ import annotations

import argparse
import json
import math
import re
from pathlib import Path

ANCHORS = json.loads(Path(__file__).with_name("anchors.json").read_text())

#: Harbor parses every value in reward.json as float|int (VerifierResult.rewards), so a
#: string or a null anywhere in it fails the whole trial with a ValidationError. Numbers
#: go here; everything a human needs goes in the sidecar next to it.
REWARD_PATH = Path("/logs/verifier/reward.json")
DETAIL_PATH = Path("/logs/verifier/airs_score.json")

# The marker upstream's evaluate.py prints, and the regex upstream's own
# test_task_folder.py uses to parse what follows it.
RESULT_RE = re.compile(r"--- EVALUATION RESULT ---\s*(\{[\s\S]*?\})")


def phi(s: float, s_opt: float) -> float:
    """The paper's log transform, ``phi(s) = -log10(|s - s_opt|)``.

    A submission that hits the optimum exactly has ``phi = +inf``; callers turn that
    into a normalised score of ``+inf`` and then clip, rather than dividing by zero.
    """
    d = abs(float(s) - float(s_opt))
    if d == 0.0:
        return math.inf
    return -math.log10(d)


def normalised_score(raw: float, s_min: float, s_sota: float, s_opt: float) -> float:
    """AIRS-Bench Eq. 2-3: ``(phi(s) - phi(s_min)) / (phi(s_sota) - phi(s_min))``.

    Unclipped on purpose -- above 1 means the run beat the published SOTA, below 0 means
    it was worse than the worst score Meta observed, and both facts are worth keeping.
    ``reward`` is the clipped copy.
    """
    lo = phi(s_min, s_opt)
    hi = phi(s_sota, s_opt)
    if not math.isfinite(lo) or not math.isfinite(hi) or hi == lo:
        raise ValueError(f"degenerate anchors: s_min={s_min} s_sota={s_sota} s_opt={s_opt}")
    top = phi(raw, s_opt)
    if math.isinf(top):
        return math.inf
    return (top - lo) / (hi - lo)


def reward_from(raw: float, s_min: float, s_sota: float, s_opt: float) -> float:
    """The normalised score clipped to Harbor's [0, 1] reward convention."""
    ns = normalised_score(raw, s_min, s_sota, s_opt)
    return max(0.0, min(1.0, ns))


def write(reward: float, ns: float | None, raw: float | None, *, valid: bool,
          error: str | None = None, extra: dict | None = None) -> None:
    # Harbor turns every key here into a reported metric and averages it across trials,
    # so constants like the anchors would clutter the leaderboard. They live in the
    # sidecar and in task.toml.
    numeric = {
        "reward": reward,
        "valid_submission": int(valid),
    }
    if ns is not None and math.isfinite(ns):
        numeric["normalized_score"] = ns
    if raw is not None:
        numeric["raw_metric"] = raw
    REWARD_PATH.parent.mkdir(parents=True, exist_ok=True)
    REWARD_PATH.write_text(json.dumps(numeric, indent=2) + "\n")

    detail = dict(ANCHORS)
    detail.update(numeric)
    detail["valid_submission"] = valid
    detail["error"] = error
    detail["normalized_score_raw"] = ns
    detail.update(extra or {})
    DETAIL_PATH.write_text(json.dumps(detail, indent=2) + "\n")
    print(json.dumps(detail, indent=2))


def invalid(reason: str) -> None:
    write(0.0, 0.0, None, valid=False, error=reason)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--stdout", type=Path)
    ap.add_argument("--exit-code", type=int, default=0)
    ap.add_argument("--invalid")
    args = ap.parse_args()

    if args.invalid:
        invalid(args.invalid)
        return
    if args.exit_code != 0:
        invalid(f"evaluate.py exited {args.exit_code}")
        return

    text = args.stdout.read_text(errors="replace") if args.stdout else ""
    m = RESULT_RE.search(text)
    if m is None:
        invalid("no '--- EVALUATION RESULT ---' block in evaluate.py stdout")
        return
    try:
        result = json.loads(m.group(1))
    except ValueError as e:
        invalid(f"unparseable evaluation result: {e}")
        return

    name = ANCHORS["metric"]
    if name in result:
        raw = result[name]
    elif len(result) == 1:
        # An upstream grader may spell the key differently from logging_info.metric;
        # a single-key result leaves no ambiguity about which number is meant.
        raw = next(iter(result.values()))
    else:
        invalid(f"metric {name!r} not in evaluation result {sorted(result)}")
        return
    if raw is None or (isinstance(raw, float) and math.isnan(raw)):
        invalid(f"metric {name} is {raw!r}")
        return

    raw = float(raw)
    ns = normalised_score(raw, ANCHORS["s_min"], ANCHORS["s_sota"], ANCHORS["s_opt"])
    write(max(0.0, min(1.0, ns)), ns, raw, valid=True, extra={"all_metrics": result})


if __name__ == "__main__":
    main()
