#!/usr/bin/env bash
# Generated by awm/adapters/airs.py for QuestionAnsweringDuoRCAccuracy. Harbor uploads this directory to /tests
# and runs this script only after the agent phase has ended.
#
# The grader itself is upstream's: tests/upstream/evaluate.py, unmodified. This script
# only reproduces the second half of upstream's evaluate_prepare.py (put the gold labels
# and the submission where evaluate.py looks for them) and then normalises the number.
set -uo pipefail

LOGDIR=/logs/verifier
mkdir -p "$LOGDIR"
EVAL_ROOT=/tmp/airs_eval
rm -rf "$EVAL_ROOT"
mkdir -p "$EVAL_ROOT/data"

score() { python3 /tests/score.py "$@"; }

# Some graders read the agent-visible splits too (e.g. the time-series tasks need the
# history), so link them in alongside the gold labels.
if [ -d /app/data ]; then
  for entry in /app/data/*; do
    [ -e "$entry" ] || continue
    ln -s "$entry" "$EVAL_ROOT/data/$(basename "$entry")"
  done
fi

if [ ! -d /tests/eval_data/test_with_labels ]; then
  score --invalid "gold labels missing: run 'python -m awm.adapters.airs stage --task QuestionAnsweringDuoRCAccuracy' on the host"
  exit 0
fi
rm -rf "$EVAL_ROOT/data/test_with_labels"
cp -r /tests/eval_data/test_with_labels "$EVAL_ROOT/data/test_with_labels"

if [ ! -f /app/submission.csv ]; then
  score --invalid "no /app/submission.csv"
  exit 0
fi
cp /app/submission.csv "$EVAL_ROOT/data/submission.csv"

cd "$EVAL_ROOT"
python3 /tests/upstream/evaluate.py --submission-file ./data/submission.csv \
  > "$LOGDIR/evaluate_stdout.txt" 2> "$LOGDIR/evaluate_stderr.txt"
rc=$?
tail -n 40 "$LOGDIR/evaluate_stdout.txt" "$LOGDIR/evaluate_stderr.txt"

score --stdout "$LOGDIR/evaluate_stdout.txt" --exit-code "$rc"
